#!/usr/bin/env python3
"""Auto-generate SCHEMA-REFERENCE.md from live database schemas.

Queries Postgres (legislation_text + provision_actors) and DuckDB (legislation)
to produce an always-current schema reference document.

Usage:
    python3 scripts/maintenance/schema_docs.py
    python3 scripts/maintenance/schema_docs.py --pg postgres://fractalaw:fractalaw@localhost:5433/fractalaw
    python3 scripts/maintenance/schema_docs.py --output docs/architecture/SCHEMA-REFERENCE.md
"""

import argparse
import os
import subprocess
import sys
from datetime import date
from pathlib import Path


def query_pg_columns(pg_url: str, table: str) -> list[dict]:
    """Query Postgres information_schema for column metadata."""
    sql = f"""
        SELECT column_name, data_type, udt_name, is_nullable, column_default
        FROM information_schema.columns
        WHERE table_name = '{table}'
        ORDER BY ordinal_position;
    """
    env = os.environ.copy()
    env["PGPASSWORD"] = pg_url.split(":")[-1].split("@")[0] if "@" in pg_url else ""

    result = subprocess.run(
        ["psql", pg_url, "-t", "-A", "-F", "|", "-c", sql],
        capture_output=True, text=True, env=env,
    )
    if result.returncode != 0:
        print(f"  WARN: Postgres query failed for {table}: {result.stderr.strip()}", file=sys.stderr)
        return []

    columns = []
    for line in result.stdout.strip().split("\n"):
        if not line.strip():
            continue
        parts = line.split("|")
        if len(parts) >= 4:
            columns.append({
                "name": parts[0].strip(),
                "type": parts[1].strip(),
                "udt": parts[2].strip(),
                "nullable": parts[3].strip(),
                "default": parts[4].strip() if len(parts) > 4 else "",
            })
    return columns


def query_pg_indexes(pg_url: str, table: str) -> list[str]:
    """Query Postgres for index definitions."""
    sql = f"""
        SELECT indexdef FROM pg_indexes
        WHERE tablename = '{table}'
        ORDER BY indexname;
    """
    result = subprocess.run(
        ["psql", pg_url, "-t", "-A", "-c", sql],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return []
    return [line.strip() for line in result.stdout.strip().split("\n") if line.strip()]


def query_pg_row_count(pg_url: str, table: str) -> int:
    """Get approximate row count from Postgres."""
    sql = f"SELECT count(*) FROM {table};"
    result = subprocess.run(
        ["psql", pg_url, "-t", "-A", "-c", sql],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return 0
    try:
        return int(result.stdout.strip())
    except ValueError:
        return 0


def query_duckdb_columns(db_path: str) -> list[dict]:
    """Query DuckDB for legislation table schema."""
    sql = "DESCRIBE legislation;"
    result = subprocess.run(
        ["duckdb", db_path, "-csv", "-c", sql],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        # Try via fractalaw CLI
        result = subprocess.run(
            ["cargo", "run", "-p", "fractalaw-cli", "--", "query", sql],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            print(f"  WARN: DuckDB query failed: {result.stderr.strip()}", file=sys.stderr)
            return []

    columns = []
    for line in result.stdout.strip().split("\n")[1:]:  # skip header
        parts = line.split(",")
        if len(parts) >= 2:
            columns.append({
                "name": parts[0].strip().strip('"'),
                "type": parts[1].strip().strip('"'),
                "nullable": parts[2].strip().strip('"') if len(parts) > 2 else "YES",
            })
    return columns


def format_pg_type(col: dict) -> str:
    """Format Postgres column type for display."""
    udt = col["udt"]
    if udt == "vector":
        return "vector(384)"
    if udt.startswith("_"):
        return f"{udt[1:].upper()}[]"
    base = col["type"]
    if base == "USER-DEFINED":
        return udt.upper()
    return base.upper().replace("CHARACTER VARYING", "VARCHAR").replace("TIMESTAMP WITH TIME ZONE", "TIMESTAMPTZ")


def generate_markdown(
    pg_url: str | None,
    duckdb_path: str | None,
) -> str:
    """Generate the full schema reference markdown."""
    lines = [
        "# Schema Reference",
        "",
        f"**Generated**: {date.today().isoformat()}",
        "**Source**: auto-generated by `scripts/maintenance/schema_docs.py` from live databases",
        "",
        "> Do not edit this file manually — it will be overwritten on next generation.",
        "> Run `python3 scripts/maintenance/schema_docs.py` to regenerate.",
        "",
    ]

    # --- Postgres: legislation_text ---
    if pg_url:
        lines.append("## Postgres: `legislation_text`")
        lines.append("")
        lines.append("Hub provision store — one row per structural unit of legal text.")
        lines.append("")

        cols = query_pg_columns(pg_url, "legislation_text")
        count = query_pg_row_count(pg_url, "legislation_text")
        if cols:
            lines.append(f"**{count:,} rows** | {len(cols)} columns")
            lines.append("")
            lines.append("| Column | Type | Nullable |")
            lines.append("|--------|------|----------|")
            for c in cols:
                typ = format_pg_type(c)
                null = "yes" if c["nullable"] == "YES" else "no"
                lines.append(f"| `{c['name']}` | `{typ}` | {null} |")
            lines.append("")

        # Indexes
        indexes = query_pg_indexes(pg_url, "legislation_text")
        if indexes:
            lines.append("### Indexes")
            lines.append("")
            lines.append("```sql")
            for idx in indexes:
                lines.append(idx)
            lines.append("```")
            lines.append("")

        # --- Postgres: provision_actors ---
        cols2 = query_pg_columns(pg_url, "provision_actors")
        count2 = query_pg_row_count(pg_url, "provision_actors")
        if cols2:
            lines.append("## Postgres: `provision_actors`")
            lines.append("")
            lines.append("Per-provision actor classifications with per-tier signal columns.")
            lines.append("")
            lines.append(f"**{count2:,} rows** | {len(cols2)} columns")
            lines.append("")
            lines.append("| Column | Type | Nullable |")
            lines.append("|--------|------|----------|")
            for c in cols2:
                typ = format_pg_type(c)
                null = "yes" if c["nullable"] == "YES" else "no"
                lines.append(f"| `{c['name']}` | `{typ}` | {null} |")
            lines.append("")

            indexes2 = query_pg_indexes(pg_url, "provision_actors")
            if indexes2:
                lines.append("### Indexes")
                lines.append("")
                lines.append("```sql")
                for idx in indexes2:
                    lines.append(idx)
                lines.append("```")
                lines.append("")

    # --- DuckDB: legislation ---
    if duckdb_path and Path(duckdb_path).exists():
        lines.append("## DuckDB: `legislation`")
        lines.append("")
        lines.append("Law-level metadata (LRT) — one row per law. Taxa aggregates, publish hashes, pipeline status.")
        lines.append("")

        cols = query_duckdb_columns(duckdb_path)
        if cols:
            lines.append(f"{len(cols)} columns")
            lines.append("")
            lines.append("| Column | Type | Nullable |")
            lines.append("|--------|------|----------|")
            for c in cols:
                null = "yes" if c["nullable"] == "YES" else "no"
                lines.append(f"| `{c['name']}` | `{c['type']}` | {null} |")
            lines.append("")

    # --- Schema notes ---
    lines.extend([
        "## Data Flow",
        "",
        "```",
        "Sertantai ──(LAT provision text)──→ Postgres (legislation_text)",
        "                                        │",
        "                                        ▼",
        "                                   DRRP pipeline",
        "                                   (parse → classify → reconcile → backfill)",
        "                                        │",
        "                                        ▼",
        "                              DuckDB (legislation) ←── law-level aggregates",
        "                                        │",
        "                                        ▼",
        "                              Zenoh publish → Sertantai",
        "```",
        "",
        "## Regenerating This Document",
        "",
        "```bash",
        "# Requires Postgres running on port 5433",
        "python3 scripts/maintenance/schema_docs.py",
        "```",
        "",
        "See `docs/architecture/README.md` for details.",
        "",
    ])

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate SCHEMA-REFERENCE.md from live databases")
    parser.add_argument(
        "--pg",
        default="postgres://fractalaw:fractalaw@localhost:5433/fractalaw",
        help="Postgres connection URL",
    )
    parser.add_argument(
        "--duckdb",
        default="data/fractalaw.duckdb",
        help="Path to DuckDB database file",
    )
    parser.add_argument(
        "--output",
        default="docs/architecture/SCHEMA-REFERENCE.md",
        help="Output file path",
    )
    parser.add_argument(
        "--no-pg",
        action="store_true",
        help="Skip Postgres (generate DuckDB section only)",
    )
    parser.add_argument(
        "--no-duckdb",
        action="store_true",
        help="Skip DuckDB (generate Postgres section only)",
    )
    args = parser.parse_args()

    pg_url = None if args.no_pg else args.pg
    duckdb_path = None if args.no_duckdb else args.duckdb

    print(f"Generating schema reference...")
    if pg_url:
        print(f"  Postgres: {pg_url}")
    if duckdb_path:
        print(f"  DuckDB: {duckdb_path}")

    md = generate_markdown(pg_url, duckdb_path)

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(md)
    print(f"  Written: {output} ({len(md.splitlines())} lines)")


if __name__ == "__main__":
    main()
